version: '3'

services:
  db:
    image: mongodb
    restart: always
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: p@ssw0rd
      MONGO_DB: mydb
  primer_api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"