version: '3'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
  primer_api:
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 8000:8000